# Generated by Django 5.1.7 on 2025-04-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingquestion',
            name='questionAnswer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
