# Generated by Django 5.1.7 on 2025-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_billingquestion_questionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingquestion',
            name='questionContent',
            field=models.CharField(default='', max_length=300),
        ),
    ]
