# Generated by Django 5.1.7 on 2025-04-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_billingquestion_questioncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingquestion',
            name='questionEmail',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='billingquestion',
            name='questionQuestioner',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
