# Generated by Django 5.1.7 on 2025-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_billingquestion_questionemail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingquestion',
            old_name='questionAnswer',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='billingquestion',
            old_name='questionContent',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='billingquestion',
            old_name='questionDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='billingquestion',
            old_name='questionQuestioner',
            new_name='Questioner',
        ),
        migrations.RenameField(
            model_name='billingquestion',
            old_name='questionType',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='billingquestion',
            name='questionEmail',
        ),
        migrations.AddField(
            model_name='billingquestion',
            name='Answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingquestion',
            name='questionerEmail',
            field=models.CharField(default='', max_length=25),
        ),
    ]
