# Generated by Django 5.1.7 on 2025-04-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_questionanswer_billingquestion_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingquestion',
            name='Title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
