# Generated by Django 5.1.7 on 2025-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_billingpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingpdf',
            old_name='pdf_file',
            new_name='PDF_file',
        ),
        migrations.RemoveField(
            model_name='billingpdf',
            name='title',
        ),
        migrations.AddField(
            model_name='billingpdf',
            name='Category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='billingpdf',
            name='Title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
