# Generated by Django 5.1.7 on 2025-05-08 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_rename_pdf_file_billingpdf_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingpdf',
            name='PDF_file',
            field=models.FileField(upload_to='questions/static/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
