# Generated by Django 5.1.7 on 2025-05-08 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_billingpdf_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingpdf',
            name='PDF_file',
            field=models.FileField(upload_to='media/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
